version: '3.8'
services:
  service_cache:
    container_name: adysa_redis
    image: redis
    restart: always
    ports:
      - '12345:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass $PASSWORD
    volumes:
      - ./data:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf
